# Importing Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import torch

# Introduction to Tensors

## Creating Tensors

### Manual-Made Tensors

In [ ]:
scalar = torch.tensor(7)

scalar

tensor(7)

In [ ]:
vector = torch.tensor([1, 2, 3])

vector

tensor([1, 2, 3])

In [ ]:
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
print(f"number of dimensions in the scalar: {scalar.ndim}")
print(f"number of dimensions in the vector: {vector.ndim}")
print(f"number of dimensions in the MATRIX: {MATRIX.ndim}")
print(f"number of dimensions in the TENSOR: {TENSOR.ndim}")

number of dimensions in the scalar: 0
number of dimensions in the vector: 1
number of dimensions in the MATRIX: 2
number of dimensions in the TENSOR: 3


In [ ]:
print(f"Size of the scalar: {scalar.shape}")
print(f"Size of the vector: {vector.shape}")
print(f"Size of the MATRIX: {MATRIX.shape}")
print(f"Size of the TENSOR: {TENSOR.shape}")

Size of the scalar: torch.Size([])
Size of the vector: torch.Size([3])
Size of the MATRIX: torch.Size([3, 3])
Size of the TENSOR: torch.Size([1, 3, 3])


### Random Tensors

In [ ]:
random_tensor = torch.rand(size=(3, 4))

random_tensor

tensor([[0.6663, 0.1646, 0.0102, 0.8713],
        [0.2386, 0.9976, 0.2447, 0.5790],
        [0.2364, 0.3269, 0.0684, 0.8633]])

In [ ]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3, 4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range Tensors and Tensors-Like

In [ ]:
range_tensor = torch.arange(1, 10)

range_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(range_tensor)

ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(range_tensor)

ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

## DTypes in Tensors

In [ ]:
int_64_bit_tensor = torch.tensor([1, 2, 3])

print(int_64_bit_tensor)
print(int_64_bit_tensor.dtype)

tensor([1, 2, 3])
torch.int64


In [ ]:
float_32_bit_tensor = torch.tensor([1, 2, 3], dtype=torch.float32)

print(float_32_bit_tensor)
print(float_32_bit_tensor.dtype)

tensor([1., 2., 3.])
torch.float32


In [ ]:
float_16_bit_tensor = torch.tensor([1, 2, 3], dtype=torch.float16)

print(float_16_bit_tensor)
print(float_16_bit_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float16)
torch.float16


In [ ]:
uint_8_bit_tensor = torch.tensor([1, 2, 3], dtype=torch.uint8)

print(uint_8_bit_tensor)
print(uint_8_bit_tensor.dtype)

tensor([1, 2, 3], dtype=torch.uint8)
torch.uint8


## Getting Information from a Tensor

In [ ]:
some_tensor = torch.rand(size=(3, 4))

some_tensor

tensor([[0.0228, 0.2293, 0.9563, 0.3134],
        [0.3123, 0.1473, 0.1016, 0.6473],
        [0.5283, 0.9659, 0.9725, 0.4849]])

In [ ]:
print(f"DType of the tensor: {some_tensor.dtype}")
print(f"Size of the tensor: {some_tensor.size()}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device of the tensor: {some_tensor.device}")

DType of the tensor: torch.float32
Size of the tensor: torch.Size([3, 4])
Shape of the tensor: torch.Size([3, 4])
Device of the tensor: cpu


## Tensor Operations

In [ ]:
tensor = torch.tensor([1, 2, 3])

tensor + 10 

tensor([11, 12, 13])

In [ ]:
tensor = torch.tensor([1, 2, 3])

tensor * 10 

tensor([10, 20, 30])

In [ ]:
tensor = torch.tensor([1, 2, 3])

tensor - 10 

tensor([-9, -8, -7])

In [ ]:
tensor = torch.tensor([1, 2, 3])

tensor / 10 

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor = torch.tensor([1, 2, 3])

tensor ** 10 

tensor([    1,  1024, 59049])

In [ ]:
tensor = torch.tensor([1, 2, 3])

torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
tensor_A = torch.rand(4, 3)

tensor_B = torch.rand(4, 3)

tensor_A, tensor_B

(tensor([[0.0629, 0.9013, 0.6815],
         [0.8348, 0.5842, 0.6101],
         [0.2359, 0.2586, 0.2580],
         [0.6255, 0.0839, 0.1258]]),
 tensor([[0.8406, 0.2462, 0.2524],
         [0.1496, 0.8607, 0.2482],
         [0.5064, 0.4726, 0.4408],
         [0.7875, 0.4836, 0.4003]]))

In [ ]:
tensor_A + tensor_B

tensor([[0.9034, 1.1475, 0.9339],
        [0.9843, 1.4449, 0.8583],
        [0.7423, 0.7312, 0.6988],
        [1.4130, 0.5675, 0.5261]])

In [ ]:
tensor_A - tensor_B

tensor([[-0.7777,  0.6551,  0.4291],
        [ 0.6852, -0.2765,  0.3619],
        [-0.2705, -0.2140, -0.1828],
        [-0.1620, -0.3997, -0.2745]])

In [ ]:
tensor_A * tensor_B

tensor([[0.0528, 0.2219, 0.1720],
        [0.1249, 0.5029, 0.1514],
        [0.1194, 0.1222, 0.1137],
        [0.4926, 0.0406, 0.0504]])

In [ ]:
tensor_A / tensor_B

tensor([[0.0748, 3.6606, 2.6997],
        [5.5806, 0.6788, 2.4580],
        [0.4658, 0.5471, 0.5852],
        [0.7943, 0.1735, 0.3143]])

In [ ]:
tensor_A ** tensor_B

tensor([[0.0977, 0.9747, 0.9077],
        [0.9733, 0.6297, 0.8846],
        [0.4812, 0.5277, 0.5503],
        [0.6911, 0.3017, 0.4362]])

## Martix Multiplication

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([4, 3]), torch.Size([4, 3]))

In [ ]:
matrix_multiplication_tensor = torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.T.shape

In [ ]:
matrix_multiplication_tensor = torch.matmul(tensor_A.T, tensor_B)

matrix_multiplication_tensor, matrix_multiplication_tensor.shape

(tensor([[0.7898, 1.1479, 0.5774],
         [1.0420, 0.8875, 0.5201],
         [0.8938, 0.8757, 0.4875]]),
 torch.Size([3, 3]))

In [ ]:
matrix_multiplication_tensor = torch.matmul(tensor_A, tensor_B.T)

matrix_multiplication_tensor, matrix_multiplication_tensor.shape

(tensor([[0.4468, 0.9543, 0.7582, 0.7581],
         [0.9995, 0.7791, 0.9678, 1.1841],
         [0.3271, 0.3219, 0.3554, 0.4141],
         [0.5782, 0.1970, 0.4119, 0.5835]]),
 torch.Size([4, 4]))

In [ ]:
tensor_A @ tensor_B.T

tensor([[0.4468, 0.9543, 0.7582, 0.7581],
        [0.9995, 0.7791, 0.9678, 1.1841],
        [0.3271, 0.3219, 0.3554, 0.4141],
        [0.5782, 0.1970, 0.4119, 0.5835]])

## Tensor Aggregation (Finding min, max, mean, sum, etc.)

In [ ]:
x = torch.arange(0, 100, 10)

x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.dtype

torch.int64

In [ ]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [ ]:
x.mean(), torch.mean(x)

RuntimeError: ignored

In [ ]:
x_float = x.type(torch.float32)

x_float

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
x_float.mean(), torch.mean(x_float)

(tensor(45.), tensor(45.))

In [ ]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

## Finding the position of min and max (argmin, argmax)

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
torch.argmin(x)

tensor(0)

In [ ]:
torch.argmax(x)

tensor(9)

In [ ]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x.min(dim=0)

torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))

In [ ]:
x.min(dim=1)

torch.return_types.min(
values=tensor([1, 4, 7]),
indices=tensor([0, 0, 0]))

In [ ]:
x.sum(dim=0)

tensor([12, 15, 18])

In [ ]:
x.sum(dim=1)

tensor([ 6, 15, 24])

## Reshaping, stacking, squeezing, unsqueezing and permuting tensors

In [ ]:
x = torch.arange(1., 10.)

x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [ ]:
x_reshaped_1 = x.reshape(shape=(3, 3))

x_reshaped_1, x_reshaped_1.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
x_reshaped_2 = x.reshape(shape=(1, 3, 3))

x_reshaped_2, x_reshaped_2.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x_reshaped_2[0, 0, 0] = 5000.

In [ ]:
x_reshaped_2

tensor([[[5.0000e+03, 2.0000e+00, 3.0000e+00],
         [4.0000e+00, 5.0000e+00, 6.0000e+00],
         [7.0000e+00, 8.0000e+00, 9.0000e+00]]])

In [ ]:
x.reshape(shape=(9, 1))

tensor([[5.0000e+03],
        [2.0000e+00],
        [3.0000e+00],
        [4.0000e+00],
        [5.0000e+00],
        [6.0000e+00],
        [7.0000e+00],
        [8.0000e+00],
        [9.0000e+00]])

In [ ]:
x.reshape(shape=(1, 9))

tensor([[5.0000e+03, 2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00, 6.0000e+00,
         7.0000e+00, 8.0000e+00, 9.0000e+00]])

In [ ]:
x.view(size=(1, 9))

tensor([[5.0000e+03, 2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00, 6.0000e+00,
         7.0000e+00, 8.0000e+00, 9.0000e+00]])

In [ ]:
x = torch.arange(1., 10.)

x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [ ]:
x = x.reshape(shape=(1, 9))

x

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
torch.stack([x, x, x], dim=0)

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[1., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
torch.vstack([x, x, x])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
torch.stack([x, x, x], dim=1)

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
x = torch.arange(1., 10.)

x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [ ]:
torch.stack([x, x, x], dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
torch.vstack([x, x, x])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
torch.stack([x, x, x], dim=1)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [ ]:
torch.hstack([x, x, x])

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
y = torch.zeros(size=(2, 1, 2, 1, 1, 2))

y_squeezed = y.squeeze()
y_squeezed.shape

torch.Size([2, 2, 2])

In [ ]:
y_unsqueezed = y_squeezed.unsqueeze(dim=1)
y_unsqueezed = y_unsqueezed.unsqueeze(dim=3)
y_unsqueezed = y_unsqueezed.unsqueeze(dim=4)
y_unsqueezed.shape

torch.Size([2, 1, 2, 1, 1, 2])

In [ ]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
tensor.permute(dims=(1, 0))

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [ ]:
tensor = torch.rand(size=(3, 4, 7))

tensor.shape

torch.Size([3, 4, 7])

In [ ]:
permuted_tensor = tensor.permute(dims=(2, 0, 1))

permuted_tensor.shape

torch.Size([7, 3, 4])

# Indxing (Selecting Data From Tensors)

In [ ]:
x = torch.arange(1, 10).reshape(shape=(1, 3, 3))

x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0, 0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0, 0, 0]

tensor(1)

In [ ]:
x[0, 0, [0, 2]]

tensor([1, 3])

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

# PyTorch and NumPy

In [ ]:
array = np.arange(1.0, 8.0)

tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)

numpy_array = tensor.numpy()

tensor, numpy_array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1

tensor, numpy_array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility

In [ ]:
random_tensor_A = torch.rand(3, 4)

random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3909, 0.2396, 0.3144, 0.7096],
        [0.0338, 0.8761, 0.4705, 0.2680],
        [0.8084, 0.1347, 0.5771, 0.4963]])
tensor([[0.2888, 0.1354, 0.1566, 0.4751],
        [0.2257, 0.5707, 0.8412, 0.1352],
        [0.8577, 0.8379, 0.1197, 0.2109]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
random_seed = 40

torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.3679, 0.8661, 0.1737, 0.7157],
        [0.8649, 0.4878, 0.5501, 0.1318],
        [0.2897, 0.0707, 0.8016, 0.3244]])
tensor([[0.3679, 0.8661, 0.1737, 0.7157],
        [0.8649, 0.4878, 0.5501, 0.1318],
        [0.2897, 0.0707, 0.8016, 0.3244]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running Tensors and PyTorch Objects on the GPUs

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.0.1+cu118


In [ ]:
torch.cuda.is_available()

True

In [ ]:
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"

In [ ]:
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
!nvidia-smi

Tue Jun  6 17:36:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
tensor = torch.tensor([1, 2, 3], device="cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = torch.tensor([1, 2, 3], device="cuda")

print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [ ]:
tensor_on_gpu = tensor.to(device)

print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
tensor_on_cpu = tensor_on_gpu.cpu()

print(tensor_on_cpu.device)

cpu


In [ ]:
tensor_on_cpu.numpy()

array([1, 2, 3])